<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../OpenSim/Framework/OpenSim.Framework.csproj" />
    <ProjectReference Include="../../../OpenSim/Services/UserAccountService/OpenSim.Services.UserAccountService.csproj" />
    <ProjectReference Include="../../../OpenSim/Services/AuthenticationService/OpenSim.Services.AuthenticationService.csproj" />
    <ProjectReference Include="../../../OpenSim/Services/InventoryService/OpenSim.Services.InventoryService.csproj" />
    <ProjectReference Include="../../../OpenSim/Data/SQLite/OpenSim.Data.SQLite.csproj" />
  </ItemGroup>
</Project>
