<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../../NexVerse/Core/NexVersePlatform.cs" Link="NexVersePlatform.cs" />
    <Compile Include="../../../NexVerse/Core/Observability/NexMetrics.cs" Link="NexMetrics.cs" />
    <Compile Include="../../../NexVerse/Core/Observability/NexTelemetry.cs" Link="NexTelemetry.cs" />
    <Compile Include="../../../NexVerse/Server/Api/NexOtlpHttpExporter.cs" Link="NexOtlpHttpExporter.cs" />
  </ItemGroup>
</Project>
