; NexVerse Deutschland - automatisch erzeugt
; Jede Region ist 256x256m und eine Kachel der 1:500 Deutschlandkarte.
; Land: 21m, Wasser: 20m, Flussbett: 19m (Standardprofil).
; WICHTIG: Ports/BaseGrid ggf. vor produktivem Einsatz anpassen.

[Freiburg West]
RegionUUID = 0e6af574-ad26-55aa-9179-f0b29aeb8643
Location = 1000,1000
SizeX = 256
SizeY = 256
InternalAddress = 0.0.0.0
InternalPort = 9200
AllowAlternatePorts = False
ExternalHostName = mainland.stadt-nexverse.de
RegionType = Mainland

[Freiburg Sued]
RegionUUID = 86c1fa90-7544-5f62-b7a6-ee97a7de142e
Location = 1001,1000
SizeX = 256
SizeY = 256
InternalAddress = 0.0.0.0
InternalPort = 9201
AllowAlternatePorts = False
ExternalHostName = mainland.stadt-nexverse.de
RegionType = Mainland

[Ulm]
RegionUUID = 6b6f3581-2c91-5db0-b41b-7afdc877f4a8
Location = 1002,1000
SizeX = 256
SizeY = 256
InternalAddress = 0.0.0.0
InternalPort = 9202
AllowAlternatePorts = False
ExternalHostName = mainland.stadt-nexverse.de
RegionType = Mainland

[Muenchen]
RegionUUID = fea35cd8-b846-52f8-942f-2e247956c87a
Location = 1003,1000
SizeX = 256
SizeY = 256
InternalAddress = 0.0.0.0
InternalPort = 9203
AllowAlternatePorts = False
ExternalHostName = mainland.stadt-nexverse.de
RegionType = Mainland

[Rosenheim]
RegionUUID = 6e415c94-b2f9-55bc-909f-917240c71ae8
Location = 1004,1000
SizeX = 256
SizeY = 256
InternalAddress = 0.0.0.0
InternalPort = 9204
AllowAlternatePorts = False
ExternalHostName = mainland.stadt-nexverse.de
RegionType = Mainland

[Passau Suedost]
RegionUUID = de3eeeeb-3e01-5a7f-8c7d-abf231d63982
Location = 1005,1000
SizeX = 256
SizeY = 256
InternalAddress = 0.0.0.0
InternalPort = 9205
AllowAlternatePorts = False
ExternalHostName = mainland.stadt-nexverse.de
RegionType = Mainland

[Saarbruecken Suedwest]
RegionUUID = 26d083cc-bbb3-5fa8-a692-a65ec8636258
Location = 1000,1001
SizeX = 256
SizeY = 256
InternalAddress = 0.0.0.0
InternalPort = 9206
AllowAlternatePorts = False
ExternalHostName = mainland.stadt-nexverse.de
RegionType = Mainland

[Karlsruhe]
RegionUUID = cc6c6256-1933-53d0-b240-1a814b26ba20
Location = 1001,1001
SizeX = 256
SizeY = 256
InternalAddress = 0.0.0.0
InternalPort = 9207
AllowAlternatePorts = False
ExternalHostName = mainland.stadt-nexverse.de
RegionType = Mainland

[Stuttgart]
RegionUUID = 7cd5f240-53e5-5acd-9f17-f184162fd15c
Location = 1002,1001
SizeX = 256
SizeY = 256
InternalAddress = 0.0.0.0
InternalPort = 9208
AllowAlternatePorts = False
ExternalHostName = mainland.stadt-nexverse.de
RegionType = Mainland

[Ingolstadt]
RegionUUID = 15633382-8778-5602-b3d0-fca48dd42b2a
Location = 1003,1001
SizeX = 256
SizeY = 256
InternalAddress = 0.0.0.0
InternalPort = 9209
AllowAlternatePorts = False
ExternalHostName = mainland.stadt-nexverse.de
RegionType = Mainland

[Passau Nordwest]
RegionUUID = a75b0993-4fd9-5724-a1b4-56ec77fa71bd
Location = 1004,1001
SizeX = 256
SizeY = 256
InternalAddress = 0.0.0.0
InternalPort = 9210
AllowAlternatePorts = False
ExternalHostName = mainland.stadt-nexverse.de
RegionType = Mainland

[Passau Ost]
RegionUUID = df1254ad-47a1-53de-8d20-de484a9b0433
Location = 1005,1001
SizeX = 256
SizeY = 256
InternalAddress = 0.0.0.0
InternalPort = 9211
AllowAlternatePorts = False
ExternalHostName = mainland.stadt-nexverse.de
RegionType = Mainland

[Saarbruecken Nordwest]
RegionUUID = 361e1b32-ec3c-54ae-b5ef-5cb1bbd195f4
Location = 1000,1002
SizeX = 256
SizeY = 256
InternalAddress = 0.0.0.0
InternalPort = 9212
AllowAlternatePorts = False
ExternalHostName = mainland.stadt-nexverse.de
RegionType = Mainland

[Wiesbaden]
RegionUUID = 0bbacaf9-0883-500f-ae76-c632f9c9fe94
Location = 1001,1002
SizeX = 256
SizeY = 256
InternalAddress = 0.0.0.0
InternalPort = 9213
AllowAlternatePorts = False
ExternalHostName = mainland.stadt-nexverse.de
RegionType = Mainland

[Wuerzburg]
RegionUUID = 6bb65d78-4c57-5e12-8f74-2ce067e88090
Location = 1002,1002
SizeX = 256
SizeY = 256
InternalAddress = 0.0.0.0
InternalPort = 9214
AllowAlternatePorts = False
ExternalHostName = mainland.stadt-nexverse.de
RegionType = Mainland

[Coburg]
RegionUUID = bff74e38-d3aa-54c9-aa51-834f2aa1fac2
Location = 1003,1002
SizeX = 256
SizeY = 256
InternalAddress = 0.0.0.0
InternalPort = 9215
AllowAlternatePorts = False
ExternalHostName = mainland.stadt-nexverse.de
RegionType = Mainland

[Hof]
RegionUUID = a53b40cc-aa56-566f-bff2-97a860948f2e
Location = 1004,1002
SizeX = 256
SizeY = 256
InternalAddress = 0.0.0.0
InternalPort = 9216
AllowAlternatePorts = False
ExternalHostName = mainland.stadt-nexverse.de
RegionType = Mainland

[Dresden Suedost]
RegionUUID = 4bae8a8e-4a6d-5288-90ca-3625cb753200
Location = 1005,1002
SizeX = 256
SizeY = 256
InternalAddress = 0.0.0.0
InternalPort = 9217
AllowAlternatePorts = False
ExternalHostName = mainland.stadt-nexverse.de
RegionType = Mainland

[Duesseldorf]
RegionUUID = fa54d747-e800-5873-ac2d-ede318e36453
Location = 1000,1003
SizeX = 256
SizeY = 256
InternalAddress = 0.0.0.0
InternalPort = 9218
AllowAlternatePorts = False
ExternalHostName = mainland.stadt-nexverse.de
RegionType = Mainland

[NexVerse-Landing]
RegionUUID = 76745459-4a32-50a8-84fc-7e16a2dd7a84
Location = 1001,1003
SizeX = 256
SizeY = 256
InternalAddress = 0.0.0.0
InternalPort = 9219
AllowAlternatePorts = False
ExternalHostName = mainland.stadt-nexverse.de
RegionType = Mainland

[Kassel]
RegionUUID = c5f946ff-f0a1-5085-ae68-5031af6f3c70
Location = 1002,1003
SizeX = 256
SizeY = 256
InternalAddress = 0.0.0.0
InternalPort = 9220
AllowAlternatePorts = False
ExternalHostName = mainland.stadt-nexverse.de
RegionType = Mainland

[Jena]
RegionUUID = 63b84928-bb82-5be9-a230-2bf105909645
Location = 1003,1003
SizeX = 256
SizeY = 256
InternalAddress = 0.0.0.0
InternalPort = 9221
AllowAlternatePorts = False
ExternalHostName = mainland.stadt-nexverse.de
RegionType = Mainland

[Chemnitz]
RegionUUID = 7ec9d7f7-7d7f-538f-abd6-d549cd3b7b73
Location = 1004,1003
SizeX = 256
SizeY = 256
InternalAddress = 0.0.0.0
InternalPort = 9222
AllowAlternatePorts = False
ExternalHostName = mainland.stadt-nexverse.de
RegionType = Mainland

[Dresden Ost]
RegionUUID = 7f5ade86-bd94-5db6-9c44-7433fac3ef32
Location = 1005,1003
SizeX = 256
SizeY = 256
InternalAddress = 0.0.0.0
InternalPort = 9223
AllowAlternatePorts = False
ExternalHostName = mainland.stadt-nexverse.de
RegionType = Mainland

[Duisburg]
RegionUUID = 6677decb-7edb-544a-bc38-7c34bd52a854
Location = 1000,1004
SizeX = 256
SizeY = 256
InternalAddress = 0.0.0.0
InternalPort = 9224
AllowAlternatePorts = False
ExternalHostName = mainland.stadt-nexverse.de
RegionType = Mainland

[Osnabrueck]
RegionUUID = 2d5949e1-6cd6-59fa-a186-b6d4033be2f5
Location = 1001,1004
SizeX = 256
SizeY = 256
InternalAddress = 0.0.0.0
InternalPort = 9225
AllowAlternatePorts = False
ExternalHostName = mainland.stadt-nexverse.de
RegionType = Mainland

[Hannover]
RegionUUID = ca05d0e8-1052-5088-a132-3163a8c59193
Location = 1002,1004
SizeX = 256
SizeY = 256
InternalAddress = 0.0.0.0
InternalPort = 9226
AllowAlternatePorts = False
ExternalHostName = mainland.stadt-nexverse.de
RegionType = Mainland

[Magdeburg]
RegionUUID = e715eef0-b350-5326-b5e8-0d854bbebe89
Location = 1003,1004
SizeX = 256
SizeY = 256
InternalAddress = 0.0.0.0
InternalPort = 9227
AllowAlternatePorts = False
ExternalHostName = mainland.stadt-nexverse.de
RegionType = Mainland

[Potsdam]
RegionUUID = f7e304b0-a24c-51cd-bcdb-60dc00c26926
Location = 1004,1004
SizeX = 256
SizeY = 256
InternalAddress = 0.0.0.0
InternalPort = 9228
AllowAlternatePorts = False
ExternalHostName = mainland.stadt-nexverse.de
RegionType = Mainland

[Cottbus]
RegionUUID = 6d7cdbb6-39d5-5ed2-a5f0-e35e6ecba52a
Location = 1005,1004
SizeX = 256
SizeY = 256
InternalAddress = 0.0.0.0
InternalPort = 9229
AllowAlternatePorts = False
ExternalHostName = mainland.stadt-nexverse.de
RegionType = Mainland

[Emden West]
RegionUUID = a5ec3e90-c2da-545b-94df-ae6abd250bde
Location = 1000,1005
SizeX = 256
SizeY = 256
InternalAddress = 0.0.0.0
InternalPort = 9230
AllowAlternatePorts = False
ExternalHostName = mainland.stadt-nexverse.de
RegionType = Mainland

[Emden Ost]
RegionUUID = a255b40d-98d5-5f13-b46d-219b7fc8145c
Location = 1001,1005
SizeX = 256
SizeY = 256
InternalAddress = 0.0.0.0
InternalPort = 9231
AllowAlternatePorts = False
ExternalHostName = mainland.stadt-nexverse.de
RegionType = Mainland

[Hamburg]
RegionUUID = e2e65628-65be-5f3e-bf6d-fc177c7dfea4
Location = 1002,1005
SizeX = 256
SizeY = 256
InternalAddress = 0.0.0.0
InternalPort = 9232
AllowAlternatePorts = False
ExternalHostName = mainland.stadt-nexverse.de
RegionType = Mainland

[Schwerin]
RegionUUID = 1a6b949a-cbf3-5298-ac3e-effe41c19c03
Location = 1003,1005
SizeX = 256
SizeY = 256
InternalAddress = 0.0.0.0
InternalPort = 9233
AllowAlternatePorts = False
ExternalHostName = mainland.stadt-nexverse.de
RegionType = Mainland

[Berlin Nord]
RegionUUID = 8a83b75e-ae36-5d32-aa42-71b01409759b
Location = 1004,1005
SizeX = 256
SizeY = 256
InternalAddress = 0.0.0.0
InternalPort = 9234
AllowAlternatePorts = False
ExternalHostName = mainland.stadt-nexverse.de
RegionType = Mainland

[Berlin Nordost]
RegionUUID = 09edb164-f3f6-574a-b70a-792bce28875a
Location = 1005,1005
SizeX = 256
SizeY = 256
InternalAddress = 0.0.0.0
InternalPort = 9235
AllowAlternatePorts = False
ExternalHostName = mainland.stadt-nexverse.de
RegionType = Mainland

[Emden Nordwest]
RegionUUID = bbc63891-3d4c-55cb-b193-fb23a6e645de
Location = 1000,1006
SizeX = 256
SizeY = 256
InternalAddress = 0.0.0.0
InternalPort = 9236
AllowAlternatePorts = False
ExternalHostName = mainland.stadt-nexverse.de
RegionType = Mainland

[Flensburg West]
RegionUUID = ed9b5a0f-7232-5bfc-a7b2-b72698881bb5
Location = 1001,1006
SizeX = 256
SizeY = 256
InternalAddress = 0.0.0.0
InternalPort = 9237
AllowAlternatePorts = False
ExternalHostName = mainland.stadt-nexverse.de
RegionType = Mainland

[Flensburg Suedost]
RegionUUID = 8379cf83-369f-590a-9250-836e93e5a9f5
Location = 1002,1006
SizeX = 256
SizeY = 256
InternalAddress = 0.0.0.0
InternalPort = 9238
AllowAlternatePorts = False
ExternalHostName = mainland.stadt-nexverse.de
RegionType = Mainland

[Rostock]
RegionUUID = 5779d7b1-9ad5-5a3c-808d-601b2b08d036
Location = 1003,1006
SizeX = 256
SizeY = 256
InternalAddress = 0.0.0.0
InternalPort = 9239
AllowAlternatePorts = False
ExternalHostName = mainland.stadt-nexverse.de
RegionType = Mainland

[Stralsund Nordost]
RegionUUID = 1a5ff894-0330-582e-a703-958c77e63efa
Location = 1004,1006
SizeX = 256
SizeY = 256
InternalAddress = 0.0.0.0
InternalPort = 9240
AllowAlternatePorts = False
ExternalHostName = mainland.stadt-nexverse.de
RegionType = Mainland

[Stralsund Ost]
RegionUUID = f37e33f1-66ee-5d99-8b66-b934e7027aa3
Location = 1005,1006
SizeX = 256
SizeY = 256
InternalAddress = 0.0.0.0
InternalPort = 9241
AllowAlternatePorts = False
ExternalHostName = mainland.stadt-nexverse.de
RegionType = Mainland

