<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="OpenSim.Region.CoreModules">
      <HintPath>../../../bin/OpenSim.Region.CoreModules.dll</HintPath>
    </Reference>
    <Reference Include="OpenSim.Framework">
      <HintPath>../../../bin/OpenSim.Framework.dll</HintPath>
    </Reference>
    <Reference Include="OpenSim.Region.Framework">
      <HintPath>../../../bin/OpenSim.Region.Framework.dll</HintPath>
    </Reference>
    <Reference Include="OpenMetaverse">
      <HintPath>../../../bin/OpenMetaverse.dll</HintPath>
    </Reference>
    <Reference Include="Nini">
      <HintPath>../../../bin/Nini.dll</HintPath>
    </Reference>
    <Reference Include="XMLRPC">
      <HintPath>../../../bin/XMLRPC.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
