<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="log4net"><HintPath>../../../bin/log4net.dll</HintPath><Private>True</Private></Reference>
    <Reference Include="Nini"><HintPath>../../../bin/Nini.dll</HintPath><Private>True</Private></Reference>
    <Reference Include="OpenMetaverse"><HintPath>../../../bin/OpenMetaverse.dll</HintPath><Private>True</Private></Reference>
    <Reference Include="OpenMetaverseTypes"><HintPath>../../../bin/OpenMetaverseTypes.dll</HintPath><Private>True</Private></Reference>
    <Reference Include="OpenMetaverse.StructuredData"><HintPath>../../../bin/OpenMetaverse.StructuredData.dll</HintPath><Private>True</Private></Reference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../../OpenSim/Framework/OpenSim.Framework.csproj" />
    <ProjectReference Include="../../../OpenSim/Services/Interfaces/OpenSim.Services.Interfaces.csproj" />
    <ProjectReference Include="../../../OpenSim/Services/Connectors/OpenSim.Services.Connectors.csproj" />
  </ItemGroup>
</Project>
