<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../../NexVerse/Core/Security/NexAccessTokens.cs" Link="NexAccessTokens.cs" />
    <Compile Include="../../../NexVerse/Core/Security/NexSecurity.cs" Link="NexSecurity.cs" />
  </ItemGroup>
</Project>
